# Generated by Django 6.1.1 on 2026-09-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='album/', verbose_name='Зураг')),
                ('caption', models.TextField(help_text='Слайд солигдоход харагдах өгүүлбэр.', verbose_name='Тайлбар өгүүлбэр')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Дараалал')),
                ('is_published', models.BooleanField(default=True, verbose_name='Нийтлэх')),
            ],
            options={
                'verbose_name': 'Албумын зураг',
                'verbose_name_plural': 'Албумын зургууд',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(db_index=True, verbose_name='Олимпиадын он')),
                ('grade', models.PositiveSmallIntegerField(choices=[(6, '6-р анги'), (7, '7-р анги'), (8, '8-р анги'), (9, '9-р анги'), (10, '10-р анги'), (11, '11-р анги'), (12, '12-р анги')], db_index=True, verbose_name='Анги')),
                ('student', models.CharField(max_length=120, verbose_name='Сурагчийн нэр')),
                ('school', models.CharField(max_length=160, verbose_name='Сургууль')),
                ('score', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Оноо')),
                ('rank', models.PositiveSmallIntegerField(blank=True, help_text='Хоосон бол оноогоор автоматаар тооцно.', null=True, verbose_name='Байр')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Тэмдэглэл')),
            ],
            options={
                'verbose_name': 'Үр дүн',
                'verbose_name_plural': 'Үр дүн',
                'ordering': ['year', 'grade', '-score', 'student'],
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(db_index=True, verbose_name='Олимпиадын он')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Дараалал')),
                ('title', models.CharField(max_length=120, verbose_name='Шатны нэр')),
                ('date_text', models.CharField(help_text='Жишээ: 2026 · 10 сарын 1–20. Хуудсан дээр яг ингэж харагдана.', max_length=60, verbose_name='Огноо (текстээр)')),
                ('date', models.DateField(blank=True, help_text='Эрэмбэлэх, тооцоолоход ашиглана.', null=True, verbose_name='Огноо')),
                ('text', models.TextField(blank=True, verbose_name='Тайлбар')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Жишээ: ["90 минут", "5 бодлого"]', verbose_name='Тагууд')),
                ('location', models.CharField(blank=True, max_length=120, verbose_name='Байршил')),
            ],
            options={
                'verbose_name': 'Олимпиадын шат',
                'verbose_name_plural': 'Олимпиадын шатууд',
                'ordering': ['year', 'order'],
                'unique_together': {('year', 'order')},
            },
        ),
    ]
